// range
export const RANGEUPDATE = 'RANGEUPDATE';

// auth
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

// snackbar
export const SNACKBARUPDATE = 'SNACKBARUPDATE';
export const SNACKBARCLOSE = 'SNACKBARCLOSE';
